# name: Node.js CI/CD

# on:
#   push:
#     branches: [ "mayank" ]

# jobs:
#   build:

#     runs-on: self-hosted

#     strategy:
#       matrix:
#         node-version: ['latest']
#         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

#     steps:
#     - uses: actions/checkout@v4
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v3
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#     - run: npm ci
#     - run: |
#         touch .env
#         echo "${{ secrets.DEV_ENV }}" > .env
#     - run: npm run build 
#     - run: pm2 start dist/main.js 
